app_name: i3wm
wm_name: i3
wm_class: i3
hotkeys:
    - name: fullscreen
      description: toggles fullscreen for focused window
      tags:
        - fullscreen
        - window
        - toggle
      keys:
        - META
        - F
    - name: exit
      description: closes focused window
      tags:
        - close
        - exit
        - quit
      keys:
        - META
        - SHIFT
        - Q
