application:
        wm_name: i3
        wm_class: i3
        hotkeys:
                - fullscreen:
                        description: toggles fullscreen for focused window
                        tags:
                                - fullscreen
                                - window
                                - toggle
                        keys:
                                - META
                                - F
                - exit:
                        description: closes focused window
                        tags:
                                - close
                                - exit
                                - quit
                        keys:
                                - META
                                - SHIFT
                                - Q

