name: build on ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: update
      run: sudo apt-get update
    - name: install deps
      run: sudo apt-get install -y qt5-default libqt5x11extras5 cmake libx11-dev xclip g++ tk-dev tk8.5-dev libqt5x11extras5-dev
    - uses: actions/checkout@v2
    - name: cd
      run: mkdir -p src/build
    - name: cmake
      run: cd src/build && cmake ..
    - name: build
      run: cd src/build && make -j8
