name: Windows build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    
    - name: pull docker image
      run: docker pull docker.pkg.github.com/darksworm/emojigun/emojigun-win-builder:latest
      
    - name: test1
      run: ls
      
    - name: test2
      run: docker run --rm -it docker.pkg.github.com/darksworm/emojigun/emojigun-win-builder:latest ls
      
    - name: build
      run: docker run --rm -it -v $(pwd):/app docker.pkg.github.com/darksworm/emojigun/emojigun-win-builder:latest /bin/bash -c '\
           cd /app/src && \
           rm -rf build; \
           mkdir build && \
           cd build && \
           i686-w64-mingw32.static-cmake .. && \
           make CROSS=i686-w64-mingw32.static -j8'

    - uses: actions/upload-artifact@master
      with:
        name: src/build/emojigun.exe
        path: output/
