name: windows build

on:
  push:
    paths-ignore:
      - ".github/workflows/bionic-build.yml"
    branches: [ master ]
  pull_request:
    paths-ignore:
      - ".github/workflows/bionic-build.yml"
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    
    - name: pull docker image
      run: docker pull docker.pkg.github.com/darksworm/emojigun/emojigun-win-builder:latest
    
    - uses: actions/checkout@v2
      
    - name: run builder container
      run: docker run -it -d --name builder -v $GITHUB_WORKSPACE:/app docker.pkg.github.com/darksworm/emojigun/emojigun-win-builder:latest
    
    - name: build
      run: docker exec builder /bin/bash -c 'cd /app/src && rm -rf build; mkdir build && cd build && i686-w64-mingw32.static-cmake .. && make CROSS=i686-w64-mingw32.static -j2'
           
    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: emojigun.exe
        path: src/build/emojigun.exe
