name: Windows build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    
    - name: pull docker image
      run: docker pull docker.pkg.github.com/darksworm/emojigun/emojigun-win-builder:latest
      
    - name: tag docker image
      run: docker tag docker.pkg.github.com/darksworm/emojigun/emojigun-win-builder:latest emojigun-builder:latest
      
    - name: chmod build script
      run: sudo chmod +x docker/build-emojigun-win.sh
      
    - name: build
      run: cd docker && sh build-emojigun-win.sh
    
    - uses: actions/upload-artifact@master
      with:
        name: src/build/emojigun.exe
        path: output/
